### PR TITLE
Day background can be changed

### PR DESCRIPTION
**Pull request by luigi37**
Day background is now changed based on first day event "bg"

### CODE REVIEW

**Comment by luigi37** [comment]
After several testing I think it's safe enough... if you want to merge the request it would be great :-)

**Comment by JWGmeligMeyling** [comment]
Thanks for your contribution! I will have a look at it/merge it this weekend.

**Comment by luigi37** [comment]
Added option to show year arrows

**Comment by JWGmeligMeyling** [comment]
#32

**Comment by luigi37** [comment]
Any good Jan?

**Comment by JWGmeligMeyling** [comment]
Looks ok! I have merged this pull request. Furthermore, I made you a contributor for my repository. This is because you have made quite some contributions now and thus have been quite involved on improving the calendar. I hope too look into the outstanding issues any time soon!

**Pull request merged**
